version: '3.9'

services:
  apigateway:
    build:
      context: ./OnlineBankingAPIGateway
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
      - "6001:6001"
    environment:
      - ASPNETCORE_URLS=http://+:6000;http://+:6001  # Force correct URL bindings   
    networks:
      - banking-network

  backend:
    build:
      context: ./OnlineBankingSOA
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5000;http://+:5001  # Force correct URL bindings
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge
