name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
   
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push API Gateway Image
      uses: docker/build-push-action@v5
      with:
        context: ./OnlineBankingAPIGateway
        file: ./OnlineBankingAPIGateway/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/onlinebanking-apigateway:latest

    - name: Build & Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./OnlineBankingSOA
        file: ./OnlineBankingSOA/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/onlinebanking-backend:latest

  compose:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
