# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: RateLimiting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Build
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore OnlineBankingSOA/OnlineBanking.sln
      
    - name: Build API
      run: dotnet build OnlineBankingAPIGateway/OnlineBankingAPIGateway.csproj --no-restore

    - name: Build Backend
      run: dotnet build OnlineBankingSOA/OnlineBanking.csproj --no-restore
      
    - id: Test
      name: Test
      run: dotnet test OnlineBankingTest/OnlineBankingTest.csproj --no-build --verbosity normal
